version: '{build}'
os: Visual Studio 2015
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: hUF1oV9rs0mn3FFcHYFLa7cHvNWDzgGHShSAtH0EoVvxv736GMRmko1H3WE5Xb3q
branches:
  only:
    - master
install:
- ps: >-
    nuget update -self

    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"

    & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-preview2-003121" -InstallDir "$env:DOTNET_INSTALL_DIR"

build_script:
- ps: ./Build.ps1
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true